// <auto-generated />
using System;
using AlicisinaWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlicisinaWebApp.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251214140850_YeniMarkalarEklendi2")]
    partial class YeniMarkalarEklendi2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("AlicisinaWebApp.Models.Brand", b =>
                {
                    b.Property<int>("brandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("brandName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("brandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            brandId = 1,
                            CategoryId = 1,
                            brandName = "BMW"
                        },
                        new
                        {
                            brandId = 2,
                            CategoryId = 1,
                            brandName = "Mercedes"
                        },
                        new
                        {
                            brandId = 3,
                            CategoryId = 2,
                            brandName = "Yamaha"
                        },
                        new
                        {
                            brandId = 4,
                            CategoryId = 2,
                            brandName = "Suzuki"
                        },
                        new
                        {
                            brandId = 5,
                            CategoryId = 2,
                            brandName = "Honda"
                        },
                        new
                        {
                            brandId = 6,
                            CategoryId = 2,
                            brandName = "Mondial"
                        },
                        new
                        {
                            brandId = 7,
                            CategoryId = 2,
                            brandName = "Kawasaki"
                        });
                });

            modelBuilder.Entity("AlicisinaWebApp.Models.Category", b =>
                {
                    b.Property<int>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("categoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("categoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            categoryId = 1,
                            categoryName = "Otomobil"
                        },
                        new
                        {
                            categoryId = 2,
                            categoryName = "Motorsiklet"
                        });
                });

            modelBuilder.Entity("AlicisinaWebApp.Models.Vehicle", b =>
                {
                    b.Property<int>("vehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("announcementDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("bodyType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("brandId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("categoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("engineDisplacement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("enginePower")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("fuelType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("gear")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("imageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("kilometer")
                        .HasColumnType("TEXT");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("price")
                        .HasColumnType("TEXT");

                    b.Property<string>("serie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("vehicleStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("vehicleId");

                    b.HasIndex("brandId");

                    b.HasIndex("categoryId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            vehicleId = 1,
                            AppUserId = "3b2e3887-72a6-440a-b0f1-c50fa6322d9f",
                            Description = "BLA BLA BLA",
                            Title = "Sahibinden Temiz 3.20i SportLine",
                            announcementDate = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            bodyType = "Sedan",
                            brandId = 1,
                            categoryId = 1,
                            color = "Mavi",
                            engineDisplacement = "1597cc",
                            enginePower = "170hp",
                            fuelType = "Benzinli",
                            gear = "Otomatik",
                            imageUrl = "/images/320i.jpg",
                            kilometer = 56000m,
                            model = "3.20i Sport Line",
                            price = 2850000m,
                            serie = "3 Serisi",
                            vehicleStatus = "İkinci el",
                            year = 2022
                        },
                        new
                        {
                            vehicleId = 2,
                            AppUserId = "3b2e3887-72a6-440a-b0f1-c50fa6322d9f",
                            Description = "BLA BLA BLA",
                            Title = "Boyasız Tramersiz E180 Exclusive",
                            announcementDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            bodyType = "Sedan",
                            brandId = 2,
                            categoryId = 1,
                            color = "Black",
                            engineDisplacement = "1595cc",
                            enginePower = "156hp",
                            fuelType = "Benzinli",
                            gear = "Otomatik",
                            imageUrl = "/images/e180.jpg",
                            kilometer = 100000m,
                            model = "E180 Exclusive",
                            price = 3250000m,
                            serie = "E Serisi",
                            vehicleStatus = "İkinci el",
                            year = 2017
                        },
                        new
                        {
                            vehicleId = 3,
                            AppUserId = "3b2e3887-72a6-440a-b0f1-c50fa6322d9f",
                            Description = "BLA BLA BLA",
                            Title = "Dosta Gider R25",
                            announcementDate = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            bodyType = "Super Sport",
                            brandId = 3,
                            categoryId = 2,
                            color = "Red",
                            engineDisplacement = "250cc",
                            enginePower = "25hp",
                            fuelType = "Benzinli",
                            gear = "Manuel",
                            imageUrl = "/images/r25.jpeg",
                            kilometer = 15000m,
                            model = "YZF R25 ABS",
                            price = 210000m,
                            serie = "-",
                            vehicleStatus = "İkinci el",
                            year = 2021
                        });
                });

            modelBuilder.Entity("AlicisinaWebApp.Models.Brand", b =>
                {
                    b.HasOne("AlicisinaWebApp.Models.Category", "category")
                        .WithMany("brand")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("AlicisinaWebApp.Models.Vehicle", b =>
                {
                    b.HasOne("AlicisinaWebApp.Models.Brand", "brand")
                        .WithMany("vehicles")
                        .HasForeignKey("brandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlicisinaWebApp.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("categoryId");

                    b.Navigation("Category");

                    b.Navigation("brand");
                });

            modelBuilder.Entity("AlicisinaWebApp.Models.Brand", b =>
                {
                    b.Navigation("vehicles");
                });

            modelBuilder.Entity("AlicisinaWebApp.Models.Category", b =>
                {
                    b.Navigation("brand");
                });
#pragma warning restore 612, 618
        }
    }
}
